server:
  port: 8084

## Consumer configuration
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock
      ## rest : Consumer starts consuming from the END of the partition
      ## earliest : Consumer starts consuming from the BEGINNING of the partition
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"